spring:
  application:
    name: chirp
  data:
    redis:
      host: "redis-12566.c245.us-east-1-3.ec2.redns.redis-cloud.com:"
      password: ${REDIS_PASSWORD}
      username: "default"
      connect-timeout: 5000ms
      timeout: 2000ms
      port: 12566
  datasource:
    url: jdbc:postgresql://aws-1-us-east-2.pooler.supabase.com:5432/postgres
    username: postgres.rqcherchzviljtcweafa
    password: ${POSTGRES_PASSWORD}
    driver: org.postgresql.Driver

    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 20000
      idle-timeout: 300000
      max-lifetime: 12000000
      validation-timeout: 5000
      pool-name: SpringBootHikariCP
      data-source-properties:
          prepareThreshold: 5
          preparedStatementCacheQueries: 256
          preparedStatementCacheSizeMiB: 5

          tcpKeepAlive: true
          socketTimeout: 30
          connectTimeout: 10
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        show_sql: true
jwt:
  secret: ${JWT_SECRET_BASE64}
  expiration-minutes: 15

chirp:
  email:
    verification:
      expiry-hours: 24
    reset-password:
      expiry-minutes: 15

nginx:
  trusted-ips:
    - "127.0.0.1"
    - "::1"
    - "172.17.0.0/16"
    - "10.0.0.5/32"